### ISSUE TITLE
Remove Usage of CreateHeapFn in MVI

### ISSUE THREAD

**Issue by bjjones** [intel/GPGMM#669]
Chromium doesn't allow usage of std::function, which is what the CreateHeapFn is defined as.

I see two options:
1) Keep this as a callback and take a dependency on chromium base::OnceCallback.
2) Get rid of the callback param and inline the code in some manner, probably will add a ResourceAllocator::CreateCommittedResource function and call it. 

2 is my preferred option since we don't have any other possible values for CreateHeapFn right now. This will probably mean some code duplication in the future when adding other methods of heap creation (I think this is what's in Dawn).

@egalli
@bbernhar - I'm not sure how much autonomy you're giving me over GPGMM issues while you're on loan. I'm assuming you'll want to have high level input until you tell me otherwise.

**Comment by bbernhar** [comment]
Perhaps we could replace `CreateHeapFn` with a simple c-style call-back instead? A more flexible function type isn't strictly required and the call-back was to guarantee residency operations happen before D3D creation (and w/o `D3D12_HEAP_FLAG_CREATE_NOT_RESIDENT`).

Happy to give feedback but do as you see fit to unblock.

**Comment by bjjones** [comment]
It looks like we _can_ do this as a C-style function pointer. Issue is we can't use lambda capture if we're assigning it to a function pointer - this means we have pass around a bunch more params and it feels awkward, although it does seem to work.

Whether I do this or just inline everything, both are significant enough deviations from the full GPGMM that my preference would be to just do what's simple - which is just putting CreateCommittedResource inline inside CreateResource.

I'm unsure what the plan is for MVI - is this expected to slowly evolve into full or some subset of GPGMM through Chromium reviews? or is it expected to be deprecated and replaced all at once later on?

**Comment by bbernhar** [comment]
Idea is to incrementally replace the MVI with a full GMM (eg. gpgmm). The problem of moving `CreateCommittedResource` outside of `CreateHeap` is that `CreateHeap` wants to prevent D3D from paging out the wrong heaps (implicitly) and needs to be created with the ID3D12Pageable, returned by `CreateCommittedResource`, it represents. The call-back itself doesn't need to capture any additional state and pass it around so a lambda is overkill.

**Comment by bjjones** [comment]
Fixed with #670
